# Generated by Django 2.2.6 on 2021-04-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210425_1613'),
        ('posts', '0005_auto_20210425_2023'),
    ]

    operations = [
    ]
